defaults:
  env: mainnet
  source:
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

apps: 

                                    
addons:
  - name: argo-cd-apps
    namespace: argocd
    autosync: true
    valueFiles:
      - values.yaml    
      - values.mainnet.yaml
  - name: external-secrets
    namespace: external-secret
    releaseName: external-secret
    autosync: false
  - name: kube-prometheus-stack
    releaseName: prometheus
    namespace: monitoring
    autosync: false
  - name: loki-stack
    namespace: monitoring
    releaseName: loki
    autosync: false 
  # - name: nginx-ingress-controller
  #   releaseName: ingress-nginx
  #   namespace: ingress-nginx
  #   autosync: false
